@id=f4d400b0-6b7d-4e12-9b7e-1b5c63c5c7d1
PUT http://localhost:5078/breakfasts/{{id}}
Content-Type: application/json

{
    "name": "Fuck Me Daddy",
    "description": "Vegan everything! Join us for a healthy breakfast..",
    "startDateTime": "2022-04-08T08:00:00",
    "endDateTime": "2022-04-08T11:00:00",
    "savory": [
        "Oatmeal",
        "Avocado Toast",
        "Omelette",
        "Salad"
    ],
    "Sweet": [
        "Cookie"
    ]
}